name: 'Merge a Branch Into a Baseline Branch'
author: "Jessica Wilson"
description: 'Given a branch name you want to merge and the branch name you want to merge into, will merge the former into the latter.'
inputs:
  branch-prefix:
    description: 'The prefix of the name of the desired branch to merge'
    required: true
    default: ''
  release-version:
    description: 'An optional version (ie. SemVer) if your branch to merge contains one'
    required: true
    default: ''
  baseline-branch:
    description: 'The branch you want to merge into. Default is master.'
    required: true
    default: 'master'
  repository-url:
    description: 'The url to the repository containing the github secret'
    required: true
# outputs:
#   release-branch-name:
#     description: 'The name of the new release branch'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'git-merge'
  color: 'orange'